imdb_links = [
    ["https://www.imdb.com/title/tt0816692", True],
    ["https://www.imdb.com/title/tt1707386", True],
    ["https://www.imdb.com/title/tt2194499", True],
    ["https://www.imdb.com/title/tt4846340", True],
    ["https://www.imdb.com/title/tt0241527", True],
    ["https://www.imdb.com/title/tt0808151", True],
    ["https://www.imdb.com/title/tt1659337", True],
    ["https://www.imdb.com/title/tt1049413", True],
    ["https://www.imdb.com/title/tt1981677", True],
    ["https://www.imdb.com/title/tt2194499", True],
    ["https://www.imdb.com/registration/signin", False],
    ["https://www.imdb.com/news/top", False],
    ["https://help.imdb.com/imdbpro?ref_=helpsect_tab", False],
    ["https://help.imdb.com/imdb?ref_=ft_con", False],
    ["https://help.imdb.com/contribution?ref_=helpsect_tab", False],
    ["https://www.imdb.com/pressroom/?ref_=ft_pr", False],
    ["https://www.imdb.com/gallery", False],
    ["https://www.imdb.com/imdbpicks", False],
    ["https://contribute.imdb.com", False],
    ["https://www.imdb.com/event/all", False]
]

agoodmovietowatch_links = [
    ["https://agoodmovietowatch.com/the-100-years-show/", True],
    ["https://agoodmovietowatch.com/the-edge-of-democracy-2019/", True],
    ["https://agoodmovietowatch.com/fyre-2019/", True],
    ["https://agoodmovietowatch.com/icarus-2017/", True],
    ["https://agoodmovietowatch.com/salt-earth-2014/", True],
    ["https://agoodmovietowatch.com/into-the-inferno-2016/", True],
    ["https://agoodmovietowatch.com/twinsters-2015/", True],
    ["https://agoodmovietowatch.com/what-happened-miss-simone-2015/", True],
    ["https://agoodmovietowatch.com/the-act-of-killing-2012/", True],
    ["https://agoodmovietowatch.com/man-on-wire-2008/", True],
    ["https://agoodmovietowatch.com/about/", False],
    ["https://agoodmovietowatch.com/login/", False],
    ["https://agoodmovietowatch.com/subscribing-to-agoodmovietowatch/", False],
    ["https://agoodmovietowatch.com/agoodmovietowatch-terms-of-use/", False],
    ["https://agoodmovietowatch.com/privacy-policy/", False],
    ["https://agoodmovietowatch.com/lists/staff-list/", False],
    ["https://agoodmovietowatch.com/mood/", False],
    ["https://agoodmovietowatch.com/genre/", False],
    ["https://agoodmovietowatch.com/tag/best/", False],
    ["https://agoodmovietowatch.com/all/", False]
]

findamovie_links = [
    ["https://find-a-movie.com/movie/3170832/Room", True],
    ["https://find-a-movie.com/movie/2980516/The-Theory-of-Everything", True],
    ["https://find-a-movie.com/movie/1937264/Now-Is-Good", True],
    ["https://find-a-movie.com/movie/0317248/City-of-God", True],
    ["https://find-a-movie.com/movie/0976051/The-Reader", True],
    ["https://find-a-movie.com/movie/0099653/Ghost", True],
    ["https://find-a-movie.com/movie/0126029/Shrek", True],
    ["https://find-a-movie.com/movie/1951265/The-Hunger-Games:-Mockingjay---Part-1", True],
    ["https://find-a-movie.com/movie/3531824/Nerve", True],
    ["https://find-a-movie.com/movie/0434409/V-for-Vendetta", True],
    ["https://find-a-movie.com/how-it-works", False],
    ["https://find-a-movie.com/add-a-movie", False],
    ["https://find-a-movie.com/find", False],
    ["https://find-a-movie.com/register", False],
    ["https://find-a-movie.com/contact", False],
    ["https://find-a-movie.com/that-moves-you", False],
    ["https://find-a-movie.com/that-makes-you-laugh", False],
    ["https://find-a-movie.com/all-movies", False],
    ["https://find-a-movie.com/that-inspires-you", False],
    ["https://find-a-movie.com/that-surprises-you", False]
]

flixboss_links = [
    ["https://flixboss.com/movie/schindler-s-list-60036359", True],
    ["https://flixboss.com/movie/the-king-s-speech-70135893", True],
    ["https://flixboss.com/movie/dallas-buyers-club-70275751", True],
    ["https://flixboss.com/movie/her-70278933", True],
    ["https://flixboss.com/movie/a-i-artificial-intelligence-60020748", True],
    ["https://flixboss.com/movie/the-book-of-eli-70114342", True],
    ["https://flixboss.com/movie/what-happened-to-monday-80146805", True],
    ["https://flixboss.com/movie/the-green-mile-60000417", True],
    ["https://flixboss.com/movie/girl-81004374", True],
    ["https://flixboss.com/movie/the-other-boleyn-girl-70083114", True],
    ["https://flixboss.com/about-flixboss", False],
    ["https://flixboss.com/profile/watchlist", False],
    ["https://flixboss.com/privacy", False],
    ["https://flixboss.com/leaving", False],
    ["https://flixboss.com/news/new-movies-series-documentaries-on-netflix-august-2019", False],
    ["https://flixboss.com/tv-series", False],
    ["https://flixboss.com/movies/western", False],
    ["https://flixboss.com/movies/family", False],
    ["https://flixboss.com/movies/action", False],
    ["https://flixboss.com/movies/stand-up/2000-2009/imdb", False]
]

justwatch_links = [
    ["https://www.justwatch.com/us/movie/a-simple-favor", True],
    ["https://www.justwatch.com/us/movie/it-2017", True],
    ["https://www.justwatch.com/us/movie/booksmart", True],
    ["https://www.justwatch.com/us/movie/men-in-black-international", True],
    ["https://www.justwatch.com/us/movie/long-shot-2019", True],
    ["https://www.justwatch.com/us/movie/captain-marvel", True],
    ["https://www.justwatch.com/us/movie/lord-of-the-rings-ii-the-two-towers", True],
    ["https://www.justwatch.com/us/movie/bohemian-rhapsody", True],
    ["https://www.justwatch.com/us/movie/captain-fantastic", True],
    ["https://www.justwatch.com/us/movie/gone-girl", True],
    ["https://www.justwatch.com/us/new", False],
    ["https://www.justwatch.com/us/watchlist", False],
    ["https://www.justwatch.com/us/about", False],
    ["https://www.justwatch.com/us/press", False],
    ["https://www.justwatch.com/us/faq", False],
    ["https://www.justwatch.com/us/imprint", False],
    ["https://www.justwatch.com/us/privacy-policy", False],
    ["https://www.justwatch.com/us/apps", False],
    ["https://www.justwatch.com/us/provider/hulu", False],
    ["https://www.justwatch.com/us/provider/amazon-prime-video/new", False]
]

metacritic_links = [
    ["https://www.metacritic.com/movie/iron-man", True],
    ["https://www.metacritic.com/movie/summertime", True],
    ["https://www.metacritic.com/movie/bride-wars", True],
    ["https://www.metacritic.com/movie/casa-grande", True],
    ["https://www.metacritic.com/movie/blackfish", True],
    ["https://www.metacritic.com/movie/black-panther", True],
    ["https://www.metacritic.com/movie/carol", True],
    ["https://www.metacritic.com/movie/rudderless", True],
    ["https://www.metacritic.com/movie/amelie", True],
    ["https://www.metacritic.com/movie/ex-machina", True],
    ["https://www.metacritic.com/about-metacritic", False],
    ["https://www.metacritic.com/game", False],
    ["https://www.metacritic.com/music", False],
    ["https://www.metacritic.com/tv", False],
    ["https://www.metacritic.com/feature", False],
    ["https://www.metacritic.com/signup", False],
    ["https://www.metacritic.com/login", False],
    ["https://www.metacritic.com/contact-us", False],
    ["https://www.metacritic.com/faq", False],
    ["https://www.metacritic.com/rss", False]
]

rottentomatoes_links = [
    ["https://www.rottentomatoes.com/m/hustlers_2019", True],
    ["https://www.rottentomatoes.com/m/1221547_alice_in_wonderland", True],
    ["https://www.rottentomatoes.com/m/spider_man_far_from_home", True],
    ["https://www.rottentomatoes.com/m/singin_in_the_rain", True],
    ["https://www.rottentomatoes.com/m/1073037_hunchback_of_notre_dame", True],
    ["https://www.rottentomatoes.com/m/aquarius", True],
    ["https://www.rottentomatoes.com/m/the_girl_with_the_dragon_tattoo_2009", True],
    ["https://www.rottentomatoes.com/m/breakfast_club", True],
    ["https://www.rottentomatoes.com/m/the_imitation_game", True],
    ["https://www.rottentomatoes.com/m/barbie_as_the_princess_and_the_pauper", True],
    ["https://www.rottentomatoes.com/about#whatisthetomatometer", False],
    ["https://www.rottentomatoes.com/faq", False],
    ["https://www.rottentomatoes.com/critics", False],
    ["https://editorial.rottentomatoes.com", False],
    ["https://www.rottentomatoes.com/showtimes/?adid=nav_TS", False],
    ["https://www.rottentomatoes.com/help_desk", False],
    ["https://editorial.rottentomatoes.com/all-time-lists", False],
    ["https://www.rottentomatoes.com/browse/opening", False],
    ["https://www.rottentomatoes.com/browse/top-dvd-streaming", False],
    ["https://editorial.rottentomatoes.com/weekly-ketchup", False]
]

themoviedb_links = [
    ["https://www.themoviedb.org/movie/243684-men-women-children", True],
    ["https://www.themoviedb.org/movie/304410-la-famille-b-lier", True],
    ["https://www.themoviedb.org/movie/284293-still-alice", True],
    ["https://www.themoviedb.org/movie/306745-freeheld", True],
    ["https://www.themoviedb.org/movie/85350-boyhood", True],
    ["https://www.themoviedb.org/movie/198277-begin-again", True],
    ["https://www.themoviedb.org/movie/212716-what-if", True],
    ["https://www.themoviedb.org/movie/80278-lo-imposible", True],
    ["https://www.themoviedb.org/movie/70706-very-good-girls", True],
    ["https://www.themoviedb.org/movie/28665-fame", True],
    ["https://www.themoviedb.org/discuss", False],
    ["https://www.themoviedb.org/discover/movie", False],
    ["https://www.themoviedb.org/account/signup", False],
    ["https://www.themoviedb.org/documentation/api", False],
    ["https://www.themoviedb.org/contribute", False],
    ["https://www.themoviedb.org/apps", False],
    ["https://www.themoviedb.org/person", False],
    ["https://www.themoviedb.org/tv", False],
    ["https://www.themoviedb.org/about/staying-in-touch", False],
    ["https://www.themoviedb.org/about", False]
]

trakt_links = [
    ["https://trakt.tv/movies/arrival-2016", True],
    ["https://trakt.tv/movies/avatar-2009", True],
    ["https://trakt.tv/movies/pretty-woman-1990", True],
    ["https://trakt.tv/movies/10-things-i-hate-about-you-1999", True],
    ["https://trakt.tv/movies/becoming-jane-2007", True],
    ["https://trakt.tv/movies/pride-prejudice-2005", True],
    ["https://trakt.tv/movies/the-way-way-back-2013", True],
    ["https://trakt.tv/movies/the-way-he-looks-2014", True],
    ["https://trakt.tv/movies/short-term-12-2013", True],
    ["https://trakt.tv/movies/wonder-2017", True],
    ["https://trakt.tv/about", False],
    ["https://trakt.tv/forums/", False],
    ["https://trakt.tv/branding", False],
    ["https://trakt.tv/auth/join", False],
    ["https://trakt.tv/vip", False],
    ["https://trakt.tv/apps", False],
    ["https://trakt.tv/discover", False],
    ["https://trakt.tv/calendars/shows", False],
    ["https://trakt.tv/movies/trending", False],
    ["https://trakt.tv/shows/trending", False]
]

tvguide_links = [
    ["https://www.tvguide.com/movies/friday-the-13th/294736/", True],
    ["https://www.tvguide.com/movies/twilight/295116/", True],
    ["https://www.tvguide.com/movies/the-hobbit-the-battle-of-the-five-armies/742689/", True],
    ["https://www.tvguide.com/movies/jurassic-world/817773/", True],
    ["https://www.tvguide.com/movies/sherlock-holmes/298127/", True],
    ["https://www.tvguide.com/movies/atomic-blonde/1094705/", True],
    ["https://www.tvguide.com/movies/murder-on-the-orient-express/126786/", True],
    ["https://www.tvguide.com/movies/bee-movie/291102/", True],
    ["https://www.tvguide.com/movies/the-fault-in-our-stars/660607/", True],
    ["https://www.tvguide.com/movies/lol/282694/", True],
    ["https://www.tvguide.com/pages/staff/", False],
    ["https://www.tvguide.com/rss/", False],
    ["https://www.tvguide.com/mobile/", False],
    ["https://www.tvguide.com/user/register/", False],
    ["https://www.tvguide.com/news/", False],
    ["https://www.tvguide.com/listings/", False],
    ["https://www.tvguide.com/watchlist/about/", False],
    ["https://www.tvguide.com/watch-this-now/", False],
    ["https://www.tvguide.com/news/emmy-nominations-2019/", False],
    ["https://www.tvguide.com/news/emmys-2019-complete-coverage/", False],
]
