# Generated by Django 2.2.7 on 2019-11-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191121_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
